# Generated by Django 4.0.6 on 2022-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='fromDate',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='website',
            name='site',
            field=models.CharField(default='detikcom', max_length=200),
        ),
        migrations.AlterField(
            model_name='website',
            name='toDate',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
